### ISSUE TITLE
fuse-overlayfs leaks file descriptors with directory creation/deletion in rootless container

### ISSUE THREAD

**Issue by castedo** [containers/fuse-overlayfs#210] opened 2020-05-17 20:46 UTC
STEPS:

1) `podman run -it --rm registry.fedoraproject.org/fedora:32`

2) Inside the container run:

```
for ((i=0; i < 262144; i++)); do
   mkdir temp && rmdir temp || break
done
```

RESULT: After about ten minutes (on my computer):

```
mkdir: cannot create directory ‘temp’: Too many open files
```
  
EXPECTED: no error, like what happens running podman above with sudo

NOTES:

1) The `262144` number was chosen because that is returned by `ulimit -Hn` on my computer. If `ulimit -Hn` is different use the different number. 

2) Run `ls /proc/$(pidof fuse-overlayfs)/fd | wc -l` to watch how soon you'll reach the `ulimit -Hn` limit and see the `Too many open files` error message.

ENVIRONMENT TESTED:

rpm version is `fuse-overlayfs-0.7.2-5.module+el8.2.0+6368+cf16aa14.x86_64`

`/etc/os-release` has `CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"`

MORE NOTES:

3) If you don't want to wait around ten minutes, you can put a file in `/etc/systemd/system.conf.d/` with contents

```
[Manager]
DefaultLimitNOFILE=1024:1024
```

and reboot (maybe just logout).

4) To be extra safe, you might want to check that the number you see from `grep open /proc/$(pidof fuse-overlayfs)/limits` is the same as `ulimit -Hn`

**Comment by giuseppe** [comment] 2020-05-18 07:35
you can also set the ulimit just for the shell process and its children with `ulimit -H  -n 1024`, that will be inherited by fuse-overlayfs.

I've lowered the limit to 1024 but I am not able to reproduce the issue.

Could you show me the output for `ls -l /proc/$(pidof fuse-overlayfs)/fd` ?

Do you see any error coming from mkdir?

While the script is running, could you also strace fuse-overlayfs with `strace -v -s 4096 -p $(pidof fuse-overlayfs)` and attach a part of the output?

**Comment by castedo** [comment] 2020-05-18 10:57
Thanks for the ulimit tip! That made it much easier for me to reproduce.

Here is the output of ls before and after the bash loop runs:
[ls-before.txt](https://github.com/containers/fuse-overlayfs/files/4643595/ls-before.txt)
[ls-after.txt](https://github.com/containers/fuse-overlayfs/files/4643602/ls-after.txt)

Here are the first and last 1000 files of what strace output while the bash look was running:
[trace-head.txt](https://github.com/containers/fuse-overlayfs/files/4643614/trace-head.txt)
[trace-tail.txt](https://github.com/containers/fuse-overlayfs/files/4643615/trace-tail.txt)

I'm not sure I understand the question about "any error coming from mkdir".
I see `mkdir: cannot create directory ‘temp’: Too many open files` in the output when the bash loop stops.

**Comment by castedo** [comment] 2020-05-18 11:11
Not sure if this is helpful, but I was poking around, and when I do "rmdir temp" after running that loop I see the error `rmdir: failed to remove 'temp': No such file or directory` even though `ls` shows `temp` in the container.
Here is the strace when that rmdir was run
[trace-rmdir.txt](https://github.com/containers/fuse-overlayfs/files/4643697/trace-rmdir.txt)

**Comment by giuseppe** [comment] 2020-05-18 15:42
thanks, do you perform any other operation between step 1 and step 2 in the reproducer?

**Comment by castedo** [comment] 2020-05-18 16:52
> thanks, do you perform any other operation between step 1 and step 2 in the reproducer?

I do not.

FWIW, sometimes, but not always, after the repro steps, I am able to get the container into a state where I am able to perform a second for loop and there is no "leak". But I have not been able to get a consistent sequence of steps that a container back into a state where the leaking does not happen. I seems rather random.

I will try these reproduction steps on two more computers and different users with RHEL 8.2 and the same version fuse-overlayfs, to see if I get a consistent reproduction on different hardware and users.

**Comment by giuseppe** [comment] 2020-05-18 17:20
when you get in the state with that many fds opened, could you try to run as root the command `echo 3 > /proc/sys/vm/drop_caches` and check immediately after the number of fuse-overlayfs open fds?
  Did it change?

**Comment by castedo** [comment] 2020-05-18 17:38
It did not change. The number of fd was 1003 after reproducing and then remained 1003 after the the drop_caches command above.

**Comment by castedo** [comment] 2020-05-18 17:53
Update: I was able to reproduce (the leak with ulimit -H -n 1024) on a different laptop running the same version of RHEL and fuse-overlayfs, but a different user with completely new and clean rootless podman config/storage.

**Comment by giuseppe** [comment] 2020-05-18 19:11
thanks for the additional info.  I was able to reproduce too.

The issue seems to happen only on RHEL, I couldn't reproduce on Fedora using exactly the same steps.

The good news is that it is  fixed upstream with b1d82eb256d4ea8c3cedf35ea28c2c120442dc88 and the patch will be included in the next update on RHEL.

I am closing the issue since there is not anything to do for the upstream project.

**Closed by giuseppe** 2020-05-18 19:11 UTC

**Comment by seferovic** [comment] 2020-06-23 14:31
@giuseppe - is this already included in the latest RHEL packages? Bugzilla ID? We are still encountering the same behavior. Thank you!

**Comment by giuseppe** [comment] 2020-06-23 14:47
@seferovic RHEL issue: https://bugzilla.redhat.com/show_bug.cgi?id=1849557

**Comment by giuseppe** [comment] 2020-06-23 15:00
> is this already included in the latest RHEL packages?

what is the package you are using?  If it is 0.7.x then no, it doesn't include the fix
