### ISSUE TITLE
chmod a-rw results in zombie directory

### ISSUE THREAD

**Issue by Frederick888** [containers/fuse-overlayfs#135] opened 2019-10-22 17:29 UTC
I noticed this issue when I was trying to run [makepkg](https://wiki.archlinux.org/index.php/Makepkg) in an overlayfs.

Here's how it can be reproduced:
```sh
[/tmp]$ mkdir overlay && cd $_
[/tmp/overlay]$ mkdir lower upper work merged
[/tmp/overlay]$ fuse-overlayfs --debug -o rw,async,exec,dev,suid,nonempty,default_permissions,allow_other,use_ino,lowerdir=./lower,upperdir=./upper,workdir=./work ./merged
uid=unchanged
uid=unchanged
upperdir=/tmp/overlay/upper
workdir=./work
lowerdir=./lower
mountpoint=./merged
FUSE library version: 3.7.0
[/tmp/overlay]$ mkdir merged/test && chmod a-rw $_
[/tmp/overlay]$ rm -rf merged/test
rm: cannot remove 'merged/test': Permission denied
[/tmp/overlay]$ ll merged upper
merged:
ls: merged/test: Permission denied
total 0
drwxr-xr-x 3 frederick frederick 60 Oct 23 04:18 .
d--x--x--x 2 frederick frederick 40 Oct 23 04:18 test

upper:
total 0
drwxr-xr-x 3 frederick frederick  60 Oct 23 04:18 .
drwxr-xr-x 6 frederick frederick 120 Oct 23 04:18 ..
d--x--x--x 2 frederick frederick  40 Oct 23 04:18 test
[/tmp/overlay]$ rm -rf merged/test
[/tmp/overlay]$ ll merged upper
merged:
ls: merged/test: Permission denied
total 0
drwxr-xr-x 3 frederick frederick 60 Oct 23 04:18 .
d--x--x--x 2 frederick frederick 40 Oct 23 04:18 test

upper:
total 0
drwxr-xr-x 3 frederick frederick  60 Oct 23 04:18 .
drwxr-xr-x 6 frederick frederick 120 Oct 23 04:18 ..
d--x--x--x 2 frederick frederick  40 Oct 23 04:18 test
```
`/tmp/overlay/merged/test` in this example cannot be deleted and it somehow shows and disappears randomly in my experiment. `chmod a+rw` also fails.

**Comment by giuseppe** [comment] 2019-10-24 13:30
does the issue happen when running fuse-overlayfs inside of a user namespace?

The issue with running it directly as you did, is that it might not have enough privileges to really delete the directory.  This use case is not really used/tested, so I'd suggest you to use it from a namespace where it has enough capabilities to delete files also when their mode doesn't allow it.

You can create a user namespace in different ways, the easiest is through `unshare -r` but then you'll have only one UID/GID available inside of the namespace, alternatively you can use `podman unshare` that will automatically adds all the additional uids/gids assigned to your user

**Comment by Frederick888** [comment] 2019-10-24 15:32
No, it doesn't happen in a user namespace. I'm actually trying to create an overlayfs over my `~/.cache`. Previously I rsync the directory to tmpfs on login (which took ~7s) and after I learnt about fuse-overlayfs through podman, I thought it would be actually a great yet easy improvement. So I don't think namespace would solve my problem (at least not easily) cos the directory is used as my `XDG_CACHE_HOME` and I need to rsync it back to hard drive before logout.

May I know whether this project is designed to be used solely by podman?

**Comment by giuseppe** [comment] 2019-10-24 15:49
no it is not designed to be used only by podman.

The issue is that if you don't run in a user namespace the fuse-overlayfs process doesn't have enough privileges to delete files when the parent directory is not writeable.  fuse-overlayfs can still be used without a user namespace but as you can see it is limited.

There are other tools for creating user namespaces, e.g. https://github.com/giuseppe/become-root

I usually do `become-root -m tmux` so that I can run the entire session and spawn easily new shells inside of the namespace.

If you don't need multiple users, you can simply use `unshare -rm tmux` and use fuse-overlayfs from there.

**Closed by giuseppe** 2019-10-24 15:49 UTC
